"""update category model for uniqueness

Revision ID: 18ade1939e6a
Revises: ffed5e6d395c
Create Date: 2025-05-15 17:36:21.771899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18ade1939e6a'
down_revision: Union[str, None] = 'ffed5e6d395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_user', 'category', ['name', 'user_id'])
    op.drop_constraint('uq_product_name_category', 'product', type_='unique')
    op.create_unique_constraint('uq_product_name_category', 'product', ['name', 'category_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_name_category', 'product', type_='unique')
    op.create_unique_constraint('uq_product_name_category', 'product', ['name', 'category_id'])
    op.drop_constraint('uq_category_name_user', 'category', type_='unique')
    # ### end Alembic commands ###
