"""add user_id as foreign key in Product and Category

Revision ID: ffed5e6d395c
Revises: b3e7acb6e391
Create Date: 2025-05-14 18:27:41.256275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ffed5e6d395c'
down_revision: Union[str, None] = 'b3e7acb6e391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'category', 'people', ['user_id'], ['id'], ondelete='CASCADE')
    
    role_enum = postgresql.ENUM('user', 'admin', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE people ALTER COLUMN role TYPE role USING role::role")
    
    op.add_column('product', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'product', 'people', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    op.alter_column('people', 'role',
               existing_type=sa.Enum('user', 'admin', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    # ### end Alembic commands ###
